authentication/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('index', views.index, name='index'),
    path('registerpage',views.registerpage, name='registerpage'),
    path('register',views.register,name='register'),
    path('',views.homepage,name='homepage'),
    path('logout',views.logout,name='logout'),
    path('experience',views.experience,name='experience'),
    

]

question/urls.py
from django.urls import path

from . import views
app_name = 'question'
urlpatterns = [
    
    path('question', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote', views.vote, name='vote'),
    # path('question/<int:question_id>/', views.indx, name='indx'),
    

]

rnd/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('question.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

question/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class CorrectChoice(models.Model):
    answer = models.ForeignKey(Question, on_delete = models.CASCADE, default = "")
    correct_choice = models.CharField(max_length=1500)
    def __str__(self):
        return self.correct_choice

authentication/views.py
from django.shortcuts import render,redirect,render_to_response

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User,auth
from django.contrib import messages




def registerpage(request):
    return render(request,'authentication/registerpage.html')


def index(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user=auth.authenticate(username=email,password=password)
        print(user)

        if user is not None:
            auth.login(request,user)
            return render(request,'authentication/homepage.html')
        else:
            messages.info(request,'Invalid Credentials')
            return redirect('index')
    else:
        return render(request,'authentication/index.html')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password = request.POST['password']
        email = request.POST['email']

        if User.objects.filter(username=email).exists():
            messages.info(request,'Email already taken')
            return redirect('registerpage')
        elif User.objects.filter(email=email).exists():
            messages.info(request,'Email Alredy taken')
            return redirect('registerpage')
        else:
            user = User.objects.create_user(first_name=first_name,last_name=last_name,username=email,password=password,email=email)
            user.save()
            print('user created')
       
        return redirect('index')
    else:
        return render(request,'authentication/registerpage.html')


def logout(request):
    auth.logout(request)
    return redirect('/')


def homepage(request):
    return render(request,'authentication/homepage.html')

def experience(request):
    return render(request,'authentication/experience.html')





     
     

question/views.py
from django.shortcuts import render
from .models import Question
from django.http import HttpResponse
from django.template import loader
from django.http import Http404

from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
# def questionpage(request):
#     return render(request,'question/questionpage.html')

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'question/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    if request.method == 'POST':
        question = Question.objects.get(pk=question_id)
        question_pk = request.POST.get('question_pk')

        choice_pk = request.POST.get('choice_pk')

        try:
            selected_choice = question.choices.get(pk=choice_pk)
        except ObjectDoesNotExist:
            raise Http404

        

        return HttpResponse("You're voting on 1 question %s." % selected_choice )

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list }
    return render(request, 'question/index.html', context)


def indx(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    
    return render(request, 'question/indx.html', {'question': question})

authentication/templates/authentication/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>RnD</title>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'authentication/css/login.css'%}">
</head>
<body>
    <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
        <div class="container">
          <div class="card login-card">
            <div class="row no-gutters">
              <div class="col-md-5">
                <img alt="login" class="login-card-img" src="{% static 'authentication/images/innovation1.jpeg' %}">
              </div>
              <div class="col-md-7">
                <div class="card-body">
                  <div class="brand-wrapper">
                    <img src="{% static 'authentication/images/logo.png'%}" alt="logo" class="logo">
                  </div>
    {% block main_content %}

    {% endblock %}
</div>
</div>
</div>
</div>
</div>
</main>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
  </html>
  

authentication/templates/authentication/base2.html
{% load static %}

<!doctype html>
<html>
	<head>
		<title>Home</title>
		<link rel="stylesheet" href="{% static 'authentication/style0.css'%}">
		<link rel="stylesheet" href="{% static 'authentication/Bootstrap/css/bootstrap.css' % }">

	</head>

	<body>
	<div id="div2">
		
		<div id="nav">
			<div id="left">
			
				<div ><img src="{% static 'authentication/images/logo.png'%}" height="60px" width="100px"></div>
				
			</div>

			<div id="right">
				<ul >
					{% if user.is_authenticated %}
					<li class="cool-link"><a href="/">Home</a></li>
					{%  else %}
					<li class="cool-link"><a href="/">Home</a></li>
					{% endif %}
					<li class="cool-link"><a href=#>Contact Us</a>
						<ul>
							<li class="cool-link" ><a href=#>Facebook</a></li>
							<li class="cool-link" ><a href=#>Facebook</a></li>
							<li class="cool-link" ><a href=#>Facebook</a></li>
							<li class="cool-link" ><a href=#>Facebook</a></li>
						</ul></li>
					
					
					
					{% if user.is_authenticated %}
					
					<li class="cool-link"><a href="question">Questions</a></li>
					<li class="cool-link"> Hello {{user.first_name}} </li>
					
					<li class="cool-link"><a href="#">Leaderboard</a></li>
					<li class="cool-link"><a href="logout">Logout</a></li>
					{%  else %}
					
					<li class="cool-link"><a href="index">Login</a></li>
					<li class="cool-link"><a href="registerpage">Register</a></li>
					<li class="cool-link"><a href="experience">Experience</a></li>
					{% endif %}
				</ul>
			</div>
			<div style="clear:both;"></div>
			</div>
			
            
            {% block maincontent %}

            {% endblock %}
	</body>
</html>

authentication/templates/authentication/experience.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Experience page of Rnd</p>
    
</body>
</html>

authentication/templates/authentication/homepage.html
{% extends 'authentication/base2.html' %}
{% block maincontent %}

{% if user.is_authenticated %}
<p>Hello!!!!</p>
{%  else %}
<div >
    <h1>ABOUT US</h1>
    <p id="p1">ContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContent</p>
    <p id="p1">ContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContent</p>
    
    </div>
    <div >
        <h1>ABOUT NIT</h1>
        <p id="p1">ContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContent</p>
        <p id="p1">ContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContentContent</p>
        
        </div>
        


{% endif %}
{% endblock %}

authentication/templates/authentication/index.html
{% extends 'authentication/base.html' %}

{% block main_content %}

    <p class="login-card-description">Sign into your account</p>
    <form action="index" method="POST">
      {% csrf_token %}
        <div class="form-group">
          <label for="email" class="sr-only">Email</label>
          <input type="email" name="email" id="email" class="form-control" placeholder="Email address">
        </div>
        <div class="form-group mb-4">
          <label for="password" class="sr-only">Password</label>
          <input type="password" name="password" id="password" class="form-control" placeholder="***********">
        </div>
        <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Login">
      </form>
      <div class="message">
        {% for message in messages %}
        <h3>{{message}}</h3>
        {% endfor %}
      </div>
      <a href="#!" class="forgot-password-link">Forgot password?</a>
      <p class="login-card-footer-text">Don't have an account? <a href="registerpage" class="text-reset">Register here</a></p>


    {% endblock %}

authentication/templates/authentication/questionpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Questions are here</p>
    <!-- {% for ques in question %}
    {{question_text.question_text}}
    {% endfor %} -->

    <form action="register" method="post">
        {% csrf_token %}
        
        <div>
          <label for="answer" class="sr-only">question</label>
          <input type="text" name="answer" id="answer" class="form-control" placeholder="answer">
        </div>
        <div class="form-group">
          <label for="last_name" class="sr-only">Last Name</label>
          <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Last Name">
        </div>
        <!-- <div class="form-group">
          <label for="username" class="sr-only">User Name</label>
          <input type="text" name="username" id="username" class="form-control" placeholder="User Name">
        </div> -->
        <div class="form-group">
          <label for="email" class="sr-only">Email</label>
          <input type="email" name="email" id="email" class="form-control" placeholder="Email address">
        </div>
</body>
</html>

authentication/templates/authentication/registerpage.html
{% extends 'authentication/base.html' %}
{% block main_content %}
              <p class="login-card-description">Register your account</p>
              <form action="register" method="post">
                  {% csrf_token %}
                  
                  <div class="form-group">
                    <label for="first_name" class="sr-only">First Name</label>
                    <input type="text" name="first_name" id="first_name" class="form-control" placeholder="First Name">
                  </div>
                  <div class="form-group">
                    <label for="last_name" class="sr-only">Last Name</label>
                    <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Last Name">
                  </div>
                  <!-- <div class="form-group">
                    <label for="username" class="sr-only">User Name</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="User Name">
                  </div> -->
                  <div class="form-group">
                    <label for="email" class="sr-only">Email</label>
                    <input type="email" name="email" id="email" class="form-control" placeholder="Email address">
                  </div>
            
                  <div class="form-group mb-4">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                  </div>
                  <input name="register" id="register" class="btn btn-block login-btn mb-4" type="submit" value="Register">
                </form>
                <div class="message">
                  {% for message in messages %}
                  <h3>{{message}}</h3>
                  {% endfor %}
                </div>
                <p class="login-card-footer-text">Have an account? <a href="index" class="text-reset">Login here</a></p>
               
         

  {% endblock %}
  

question/templates/question/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'question:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ forloop.counter }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Answer">
</form>

question/templates/question/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'question:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
        {{ latest_question_list }}
        {{question}}
        
        
</body>
</html>

question/templates/question/indx.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- {% for q in ques %}
    {{ q }}
    {% endfor %} -->
    <!-- <h1>{{ question.question_text }}</h1> -->
    <h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'question:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Answer">
</form>
</body>
</html>